server:
  port: 8401

spring:
  application:
    name: iching-monitor-admin
  security:
    user:
      name: iching
      password: 123456
  boot:
    admin:
      ui:
        title: ${spring.application.name}